/**
 * GENERATED by scripts/scrape-blog.mjs from eratree.io/blog — do not hand-edit.
 * Re-run the script to refresh.
 */

export type ArticleSection = {
  heading: string;
  paragraphs: string[];
};

export type FullArticle = {
  slug: string;
  title: string;
  readingTime: string;
  excerpt: string;
  image: { src: string; alt: string; width: number; height: number };
  /** True when the image is the wordmark stand-in, which needs padding not cropping. */
  logo: boolean;
  intro: string[];
  sections: ArticleSection[];
};

export const articles: FullArticle[] = [
  {
    slug: "how-to-buy-bitcoin",
    title: "How to Buy Bitcoin",
    readingTime: "2 min read",
    excerpt: "Bitcoin was launched in 2009, and more than fifteen years later it has evolved from a niche experiment into a globally recognized financial asset. Over that time, Bitcoin has steadily gained credibility as its network has proven resilient across multiple market cycles, regulatory scrutiny, and periods of extreme volatility. Today, Bitcoin is increasingly viewed not just as a speculative instrument, but as an asset earning its place within modern portfolio allocation, alongside equities, commodities, and alternative investments.",
    image: { src: "/images/blog/how-to-buy-bitcoin.jpg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Bitcoin was launched in 2009, and more than fifteen years later it has evolved from a niche experiment into a globally recognized financial asset. Over that time, Bitcoin has steadily gained credibility as its network has proven resilient across multiple market cycles, regulatory scrutiny, and periods of extreme volatility. Today, Bitcoin is increasingly viewed not just as a speculative instrument, but as an asset earning its place within modern portfolio allocation, alongside equities, commodities, and alternative investments.",
    ],
    sections: [
      {
        heading: "THE HISTORY",
        paragraphs: [
          "Bitcoin was introduced in 2009 as a decentralized digital currency designed to operate without banks, governments, or centralized control. In its early years, it was primarily used by technologists and niche communities, with little market value and limited real-world adoption. Over time, Bitcoin survived multiple boom-and-bust cycles, regulatory scrutiny, and technical stress tests, while its network security, liquidity, and global user base continued to grow. This history of resilience has been central to Bitcoin's evolution from an experimental technology into a widely recognized digital asset.",
        ],
      },
      {
        heading: "THE GROWTH",
        paragraphs: [
          "As Bitcoin matured, an entire industry developed around it. Large-scale mining networks now support the Bitcoin blockchain, providing security through significant capital investment in hardware, energy infrastructure, and global operations. This industrialization of mining has reinforced Bitcoin's reliability and made the network increasingly resilient over time.",
          "In parallel, Bitcoin has become more tightly integrated with traditional financial markets through regulated products such as spot ETFs and the rise of digital asset treasuries held by public companies. Together, these developments reflect how Bitcoin has moved beyond a standalone technology and into a fully formed financial ecosystem that bridges on-chain infrastructure with traditional capital markets.",
        ],
      },
      {
        heading: "ERATREE",
        paragraphs: [
          "For high-net-worth individuals, family offices, and institutional buyers, acquiring Bitcoin often requires a higher standard of privacy, execution quality, and trust than public exchanges can offer. EraTree is built to meet these needs through an OTC execution model that prioritizes discretion, reliability, and deep liquidity.",
          "By providing tailored trade execution, flexible settlement options, and relationship-driven service, EraTree enables clients to buy Bitcoin efficiently and securely, without market impact or operational complexity, within a professional, institutional-grade framework.",
        ],
      },
    ],
  },
  {
    slug: "stablecoins-not-all-created-equal",
    title: "Stablecoins: Not All Created Equal..",
    readingTime: "2 min read",
    excerpt: "While stablecoins are often grouped together under a single label, not all stablecoins are built the same. They differ meaningfully in how they maintain their peg, the assets that back them, and the regulatory standards they operate under. Some are fully backed by cash and short-term government securities, while others rely on on-chain collateral or algorithmic mechanisms that introduce additional layers of complexity.",
    image: { src: "/images/blog/stablecoins-not-all-created-equal.jpg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "While stablecoins are often grouped together under a single label, not all stablecoins are built the same. They differ meaningfully in how they maintain their peg, the assets that back them, and the regulatory standards they operate under. Some are fully backed by cash and short-term government securities, while others rely on on-chain collateral or algorithmic mechanisms that introduce additional layers of complexity.",
      "These design choices matter. The engineering behind a stablecoin directly impacts its resilience, transparency, and risk profile, particularly during periods of market stress. For participants in OTC markets, understanding these differences is essential, as the structure of a stablecoin can influence liquidity, counterparty risk, and settlement reliability.",
    ],
    sections: [
      {
        heading: "FIAT BACKED",
        paragraphs: [
          "At the highest tier are fiat-backed stablecoins, which are typically supported by cash, cash equivalents, and short-term government securities held with regulated custodians. These stablecoins are designed to closely mirror traditional dollars while benefiting from blockchain-based settlement, and they are generally favored by institutions and OTC desks due to their transparency and liquidity.",
        ],
      },
      {
        heading: "CRYPTO COLLATERALIZED",
        paragraphs: [
          "Instead of being backed by cash held in a bank, these assets are backed by on-chain crypto assets such as ETH and other approved collateral that users lock into smart contracts. To account for crypto price volatility, the system requires these positions to be overcollateralized, meaning more value is deposited than the amount of stablecoins issued. If collateral values fall below required thresholds, positions are automatically liquidated to protect the peg.",
          "Dai (DAI) is a prominent crypto-collateralized stablecoin with a current market cap of $4.2B.",
          "Terra USD (UST) was an alternative crypto-collateralized model that collapsed to a value near $0 because of insufficient value backing the price of the asset, destroying market value alongside Terra Luna in 2021.",
        ],
      },
      {
        heading: "ALGORITHMIC",
        paragraphs: [
          "Another tier consists of algorithmic or partially algorithmic stablecoins, which rely on supply and demand mechanisms, incentives, or secondary tokens to maintain their peg. Rather than being fully backed by reserve assets, these stablecoins depend on market behavior and protocol design to remain stable. While innovative, they carry higher structural risk and have historically been more fragile during rapid market drawdowns.",
          "Ethena USDe (USDe) is an intriguing example of financial engineering where the collateral backing the stablecoin is an aggregated pool of capital which maintains a 'Delta Neutral' exposure to Ethereum (ETH).",
          "Stablecoins are not a monolithic asset class. They span a wide range of designs, from fully fiat-backed models to crypto-collateralized, algorithmic, and hybrid structures, each with its own tradeoffs around transparency, resilience, and risk. The engineering choices behind a stablecoin matter, particularly in high-volume or high-stakes environments, where liquidity, redemption certainty, and operational reliability are non-negotiable. Understanding these differences is essential for anyone using stablecoins beyond casual transfers.",
          "For institutions and OTC desks like EraTree, these considerations naturally lead to USDC as the preferred settlement asset. Its regulated reserve structure, deep liquidity, and broad acceptance across exchanges, custodians, and banking partners make it uniquely suited for large-scale transactions and liquidity management. While innovation across stablecoin design continues, USDC remains the clear standard for institutional-grade stability, providing the confidence and infrastructure required to move capital efficiently and securely in modern digital markets.",
        ],
      },
    ],
  },
  {
    slug: "crypto-industry-otc",
    title: "Crypto Industry: OTC",
    readingTime: "2 min read",
    excerpt: "The crypto industry has expanded rapidly in recent years, attracting new sources of capital and a broader range of market participants. ETF issuers, digital asset treasuries, exchanges, service providers, family offices, and high-net-worth individuals are increasingly active in digital asset markets, each with unique liquidity and execution needs.",
    image: { src: "/images/eratree-logo-dark.svg", alt: "", width: 478, height: 418 },
    logo: true,
    intro: [
      "The crypto industry has expanded rapidly in recent years, attracting new sources of capital and a broader range of market participants. ETF issuers, digital asset treasuries, exchanges, service providers, family offices, and high-net-worth individuals are increasingly active in digital asset markets, each with unique liquidity and execution needs.",
      "This growing institutionalization has created strong demand for professional market infrastructure, positioning OTC desks like EraTree as essential partners for efficient, discreet, and scalable crypto liquidity management.",
    ],
    sections: [
      {
        heading: "SERVICING THE PUBLIC MARKET",
        paragraphs: [
          "As public market participation in crypto grows, OTC desks play a critical role in bridging traditional financial structures with on-chain liquidity. ETF issuers, for example, require reliable access to deep spot liquidity to support creations and redemptions without disrupting open markets. This includes sourcing large blocks of assets efficiently, minimizing slippage, and settling within tight operational windows.",
          "OTC desks provide a discreet execution layer that allows ETF issuers to manage inflows and outflows smoothly, while maintaining price integrity and operational consistency.",
          "Digital asset treasuries have a different, but equally demanding, set of needs. DATs actively manage large crypto balance sheets and require flexible liquidity to accumulate, rebalance, or deploy capital across market cycles. This often involves large transactions, multi-asset settlement, and coordination between fiat, stablecoins, and crypto-native rails.",
        ],
      },
      {
        heading: "ADDRESSING PRIVATE MARKETS",
        paragraphs: [
          "Private markets remain a core pillar of crypto liquidity, operating alongside public venues but serving a distinct set of participants and needs. While exchanges excel at price discovery for smaller, continuous flows, many market participants require discretion, flexibility, and customized settlement that cannot be achieved through open order books.",
          "Crypto exchanges often rely on OTC desks to manage treasury flows, rebalance inventories, and source liquidity without impacting order books, particularly during periods of elevated volatility or large directional flows.",
          "Family offices approach the market with longer time horizons and bespoke requirements, often prioritizing discretion, tailored execution, and flexible settlement options across fiat, stablecoins, and digital assets.",
          "High-net-worth individuals similarly value privacy, execution quality, and relationship-driven service when moving meaningful size. For these participants, OTC desks provide a critical layer of infrastructure that delivers access to deep liquidity while avoiding the frictions, visibility, and market impact associated with public exchanges.",
        ],
      },
      {
        heading: "ERATREE",
        paragraphs: [
          "OTC desks like EraTree are purpose-built to support both use cases by providing institutional-grade execution, tailored liquidity solutions, and seamless settlement infrastructure.",
        ],
      },
    ],
  },
  {
    slug: "bitcoin-monetary-salability",
    title: "Bitcoin: Monetary Salability",
    readingTime: "2 min read",
    excerpt: "When evaluating monetary assets, salability is often assessed across two key dimensions: time and space. Salability across time refers to an asset's ability to preserve value over long periods, maintaining purchasing power rather than eroding through dilution or decay.",
    image: { src: "/images/blog/bitcoin-monetary-salability.jpg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "When evaluating monetary assets, salability is often assessed across two key dimensions: time and space. Salability across time refers to an asset's ability to preserve value over long periods, maintaining purchasing power rather than eroding through dilution or decay.",
      "Salability across space reflects how easily and efficiently an asset can be moved between counterparties or jurisdictions, including the costs, frictions, and risks involved in transfer. These two properties are central to understanding why certain assets function better as stores of value and settlement instruments than others.",
    ],
    sections: [
      {
        heading: "FIAT SALABILITY",
        paragraphs: [
          "Fiat currencies generally exhibit acceptable salability across space, as they are widely accepted, digitally transferable, and integrated into global banking and payment networks. Funds can move between accounts, institutions, and jurisdictions with relative ease, especially within established financial systems.",
          "However, fiat currencies perform poorly in terms of salability across time. Because their supply can expand without a fixed limit, purchasing power tends to erode over long periods, meaning value is not reliably preserved. This makes fiat effective for short-term transactions, but structurally weak as a long-term store of value.",
        ],
      },
      {
        heading: "METAL SALABILITY",
        paragraphs: [
          "Precious metals tend to perform well in terms of salability across time, as their supply grows slowly and they have historically retained purchasing power over long periods. Gold and silver have served as stores of value for centuries, largely because they are difficult to produce and resistant to debasement.",
          "However, metals exhibit poor salability across space. Moving physical bullion is costly, slow, and logistically complex, requiring secure transportation, storage, and verification. These frictions make metals impractical for efficient settlement or global value transfer, especially at scale.",
        ],
      },
      {
        heading: "BITCOIN SALABILITY",
        paragraphs: [
          "Bitcoin excels in salability across both time and space. Its fixed supply and predictable issuance schedule protect it from dilution, allowing it to preserve value over long periods in a way that fiat currencies cannot.",
          "At the same time, Bitcoin is natively digital and globally accessible, enabling value to be transferred across borders in minutes without reliance on banks, intermediaries, or physical transport. This combination of long-term scarcity and low-friction global mobility gives Bitcoin a level of monetary efficiency that neither fiat currencies nor precious metals are able to achieve.",
        ],
      },
    ],
  },
  {
    slug: "how-to-buy-stablecoins",
    title: "How to Buy Stablecoins",
    readingTime: "2 min read",
    excerpt: "Stablecoins emerged in the mid-2010s as a solution to one of crypto's challenges: volatility. While early digital assets proved the viability of blockchain networks, price instability limited their usefulness for payments, settlement, and treasury management.",
    image: { src: "/images/blog/how-to-buy-stablecoins.png", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Stablecoins emerged in the mid-2010s as a solution to one of crypto's challenges: volatility. While early digital assets proved the viability of blockchain networks, price instability limited their usefulness for payments, settlement, and treasury management.",
      "Over time, stablecoins evolved into a core piece of digital financial infrastructure, offering blockchain-native assets that maintain stable value while retaining the speed and flexibility of crypto rails. Today, stablecoins are increasingly recognized as a foundational component of modern digital markets and institutional capital flows.",
    ],
    sections: [
      {
        heading: "THE HISTORY",
        paragraphs: [
          "The first stablecoins appeared around 2014, with early designs focused on pegging digital tokens to fiat currencies like the US dollar. While initial implementations varied in quality and transparency, the concept proved essential. The launch of USDC in 2018, issued by Circle, marked a major step forward for the industry.",
          "Over time, USDC earned trust through regular attestations, clear redemption mechanisms, and deep integration with both crypto-native platforms and traditional financial institutions. This evolution helped shift stablecoins from experimental tools into credible digital versions of fiat currency.",
        ],
      },
      {
        heading: "THE GROWTH",
        paragraphs: [
          "As stablecoins matured, the surrounding ecosystem expanded rapidly. Today, stablecoins are used for trading, cross-border payments, settlement, treasury management, and increasingly as programmable money within on-chain applications. USDC in particular has become a preferred settlement asset for institutions due to its transparency, regulatory posture, and widespread acceptance across exchanges, custodians, payment processors, and blockchain networks.",
          "At the same time, stablecoins have become deeply integrated with traditional financial markets. Payment processors, fintech platforms, and institutional products now rely on stablecoins as a bridge between on-chain activity and legacy systems. The rise of spot crypto ETFs, tokenized funds, digital asset treasuries, and AI-driven payment systems has further reinforced stablecoins as a neutral settlement layer that operates globally, continuously, and at scale.",
          "What began as a trading tool has evolved into a core financial primitive.",
        ],
      },
      {
        heading: "ERATREE",
        paragraphs: [
          "For institutions, family offices, and high-net-worth individuals, accessing stablecoins requires more than a retail on-ramp. It demands reliable liquidity, professional execution, and trusted counterparties. EraTree is built to support these needs through an OTC model that prioritizes discretion, efficiency, and operational certainty.",
          "EraTree provides clients with seamless access to stablecoins like USDC, offering tailored execution, flexible settlement across fiat and crypto rails, and institutional-grade service. Whether supporting treasury operations, settlement workflows, or strategic allocation, EraTree enables clients to deploy and manage stablecoin liquidity within a private, secure, and professionally managed framework.",
        ],
      },
    ],
  },
  {
    slug: "stablecoins-institutional-integration",
    title: "Stablecoins: Institutional Integration",
    readingTime: "3 min read",
    excerpt: "Stablecoins are rapidly becoming a core component of institutional financial infrastructure, largely because they operate on a 24/7, 365 basis. Unlike traditional financial rails that are constrained by banking hours, settlement windows, and geographic limitations, stablecoins allow capital to move continuously with near-instant finality. As a result, stablecoins are increasingly viewed not just as payment tools, but as programmable cash designed for modern markets.",
    image: { src: "/images/blog/stablecoins-institutional-integration.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Stablecoins are rapidly becoming a core component of institutional financial infrastructure, largely because they operate on a 24/7, 365 basis. Unlike traditional financial rails that are constrained by banking hours, settlement windows, and geographic limitations, stablecoins allow capital to move continuously with near-instant finality. As a result, stablecoins are increasingly viewed not just as payment tools, but as programmable cash designed for modern markets.",
      "Major asset managers are now actively deploying capital on blockchain infrastructure, signaling a clear move toward tokenized finance. A notable example is BUIDL, BlackRock's on-chain money market fund, which demonstrates how traditional financial products can be issued, settled, and managed directly on public blockchains.",
    ],
    sections: [
      {
        heading: "BLACKROCK BUIDL",
        paragraphs: [
          "The BlackRock USD Institutional Digital Liquidity Fund, known as BUIDL, is the world's first large-scale tokenized money market fund issued on public blockchains. It is structured to seek current income consistent with liquidity and principal stability by investing in traditional cash equivalents such as U.S. Treasury bills, cash, and similar short-duration instruments, while issuing ownership in token form on blockchain networks like Ethereum and Solana. At the time of writing, it currently has a market capitalization of 1.7B.",
          "Qualified institutional investors can subscribe to and trade BUIDL tokens, which remain pegged to a $1 value while paying daily dividends reflective of underlying yields. Because BUIDL is tokenized, it benefits from instant settlement, transparent on-chain transferability, and broader accessibility. Further, it can be exchanged for USDC 24/7 365 - permitting liquidity on demand.",
          "The product represents a major step in bridging traditional finance with blockchain infrastructure by bringing regulated, yield-bearing institutional assets on-chain, and highlights growing institutional adoption of digital financial products.",
        ],
      },
      {
        heading: "FRANKLIN TEMPLETON",
        paragraphs: [
          "Franklin Templeton's BENJI token represents a digitized share of the Franklin OnChain U.S. Government Money Fund (FOBXX), a regulated U.S. money market fund invested primarily in government securities, cash, and fully collateralized repurchase agreements. Each BENJI token equates to one share of the fund, with its ownership and transferability recorded on public blockchain networks while maintaining the underlying legal and regulatory framework of a traditional mutual fund. The market capitalization, at the time of writing, is currently 825mm.",
          "The product offers the familiar principal stability and daily yield generation associated with money market funds, combined with faster settlement, real-time transparency, and on-chain transferability that traditional mutual funds cannot provide. Its development marks a meaningful step toward broader institutional participation in on-chain investment instruments while preserving regulatory integrity and yield-bearing characteristics.",
        ],
      },
      {
        heading: "OTHER NOTABLE ASSET MANAGERS",
        paragraphs: [
          "Beyond BlackRock and Franklin Templeton, a growing group of established asset managers and financial institutions are actively shaping the real-world asset tokenization landscape. Key players include WisdomTree (developing tokenized fund and ETF structures), Fidelity Investments (expanding digital asset products), Apollo Global Management (issuing tokenized credit via regulated systems), Securitize (enabling compliant tokenization setups), JPMorgan Onyx (handling cross-border institutional remittance), and BNY Mellon (supporting tokenized infrastructure).",
          "Together, these firms highlight that RWA tokenization is no longer experimental, but an emerging institutional standard built around regulated products and blockchain-native settlement.",
        ],
      },
    ],
  },
  {
    slug: "crypto-industry-payment",
    title: "Crypto Industry: Payment",
    readingTime: "2 min read",
    excerpt: "Payment processors are increasingly embracing crypto as digital assets move from speculation to real-world utility. Companies are now processing a growing volume of crypto-based payments, reflecting broader acceptance of blockchain rails for settlement and value transfer. As stablecoins and on-chain payments mature, traditional payment providers are integrating crypto to offer faster, more global, and more efficient payment infrastructure for businesses and consumers alike.",
    image: { src: "/images/blog/crypto-industry-payment.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Payment processors are increasingly embracing crypto as digital assets move from speculation to real-world utility. Companies are now processing a growing volume of crypto-based payments, reflecting broader acceptance of blockchain rails for settlement and value transfer. As stablecoins and on-chain payments mature, traditional payment providers are integrating crypto to offer faster, more global, and more efficient payment infrastructure for businesses and consumers alike.",
    ],
    sections: [
      {
        heading: "STRIPE",
        paragraphs: [
          "Stripe has become a significant player in both traditional and crypto-linked payments. In 2024 Stripe processed roughly $1.4 trillion in total payment volume, serving millions of merchants across more than 50 countries.",
          "On the crypto side, Stripe now supports stablecoin payments, including USDC on networks such as Ethereum, Polygon, and Base, allowing customers to pay with crypto wallets while Stripe settles the funds into merchants' Stripe balances in U.S. dollars. The company has also expanded its stablecoin capabilities to include recurring subscription billing in USDC.",
          "In 2025 alone, Stripe's stablecoin transactions have grown rapidly, surpassing $100 million in USDC transfers across multiple blockchains as adoption of digital-asset payments grows.",
        ],
      },
      {
        heading: "X402",
        paragraphs: [
          "A new HTTP standard, developed by Coinbase, is an open protocol designed to make payments native to the internet by embedding stablecoin settlement directly into HTTP using the long-reserved 402 Payment Required status code.",
          "This matters for AI because autonomous agents need money that moves as fast as software, with predictable unit-of-account pricing, near-instant settlement, and minimal overhead, which is exactly what stablecoins like USDC provide.",
          "As AI agents increasingly pay for APIs, data, compute, and digital services on demand, x402 is positioned to expand as a standard for machine-to-machine commerce, enabling pay-per-request business models without accounts, subscriptions, or manual checkout.",
        ],
      },
      {
        heading: "CLOSING THOUGHTS",
        paragraphs: [
          "Stablecoins are becoming deeply embedded into the global financial system, extending well beyond their original use cases in trading and settlement. For humans, they now function as digital dollars that move instantly, operate 24/7, and integrate seamlessly with banks, payment processors, and on-chain financial products.",
          "At the same time, stablecoins are emerging as the native currency for AI-driven systems, where autonomous software agents need a reliable, programmable, and dollar-denominated medium of exchange to pay for data, compute, APIs, and services in real time.",
        ],
      },
    ],
  },
  {
    slug: "bitcoin-absolutely-scarce",
    title: "Bitcoin: Absolutely Scarce",
    readingTime: "2 min read",
    excerpt: "Throughout history, investors have sought assets that are scarce, durable, and resistant to dilution. Gold and silver have long filled this role, largely because their supply grows slowly and extracting new material requires significant time, capital, and effort.",
    image: { src: "/images/blog/bitcoin-absolutely-scarce.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Throughout history, investors have sought assets that are scarce, durable, and resistant to dilution. Gold and silver have long filled this role, largely because their supply grows slowly and extracting new material requires significant time, capital, and effort.",
      "However, despite their relative scarcity, the supply of precious metals is not fixed. New deposits can be discovered, mining technology can improve, and higher prices can incentivize additional production, all of which expand supply over time.",
      "Bitcoin represents a fundamentally different model of scarcity. Its supply is mathematically capped at 21 million coins, enforced by code rather than geology or economics. No amount of demand, price appreciation, or technological advancement can increase that limit. This absolute scarcity sets Bitcoin apart from all prior monetary assets.",
    ],
    sections: [
      {
        heading: "CONCEPT: ABUNDANCE",
        paragraphs: [
          "Fiat currencies operate on a model of abundance rather than scarcity. There is no fixed limit to the amount of currency that can exist within a fiat-based economy, as supply is determined by central banks and monetary policy rather than hard constraints. New money can be created to respond to economic conditions, finance government spending, or stabilize financial systems, often at the discretion of policymakers.",
          "While this flexibility can be useful in the short term, it also means fiat currencies are inherently expandable, with purchasing power that can be diluted over time through sustained increases in money supply.",
        ],
      },
      {
        heading: "CONCEPT: RELATIVE SCARCITY",
        paragraphs: [
          "Precious metals such as gold and silver exist within a framework of relative scarcity. Their supply is limited by natural availability, geological constraints, and the economic viability of extraction, rather than by an absolute cap. As prices rise, previously unprofitable deposits can become economical, new reserves can be discovered, and advances in mining and processing technology can increase output.",
          "This means that while precious metals are scarce and difficult to produce, their supply can still expand over time in response to demand and incentives.",
        ],
      },
      {
        heading: "CONCEPT: ABSOLUTE SCARCITY",
        paragraphs: [
          "Bitcoin exists within a framework of absolute scarcity. Its supply is governed by a transparent algorithm that enforces a hard cap of 21 million coins, embedded directly into the network's consensus rules. This limit is not influenced by price, demand, or technological progress, and altering it would require overwhelming global agreement from participants who are economically incentivized to preserve scarcity.",
          "As a result, Bitcoin's supply schedule is widely regarded as highly unlikely to ever change, making it the first monetary asset defined by mathematically enforced scarcity rather than policy decisions or physical constraints.",
        ],
      },
      {
        heading: "BITCOIN ≠ CRYPTO",
        paragraphs: [
          "This distinction highlights a key difference between Bitcoin and the broader crypto market. Bitcoin should not be generalized as interchangeable with other cryptocurrencies, as most digital assets do not have fixed supply caps and can be expanded through governance decisions, emissions changes, or protocol upgrades.",
          "In many cases, supply is flexible by design, prioritizing utility or incentives over strict scarcity. Bitcoin's immutable supply cap sets it apart from this backdrop, positioning it as a uniquely scarce digital asset rather than simply another token within the crypto ecosystem.",
        ],
      },
    ],
  },
  {
    slug: "stablecoins-the-basics",
    title: "Stablecoins: The Basics",
    readingTime: "2 min read",
    excerpt: "Stablecoins are a class of digital assets designed to maintain a stable value, most commonly by being pegged to a fiat currency like the US dollar. Unlike traditional cryptocurrencies that experience significant price volatility, stablecoins aim to combine the price stability of cash with the speed, transparency, and programmability of blockchain technology:",
    image: { src: "/images/blog/stablecoins-the-basics.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Stablecoins are a class of digital assets designed to maintain a stable value, most commonly by being pegged to a fiat currency like the US dollar. Unlike traditional cryptocurrencies that experience significant price volatility, stablecoins aim to combine the price stability of cash with the speed, transparency, and programmability of blockchain technology:",
      "These digital assets have become a foundational layer of modern digital finance, enabling everything from crypto trading and cross-border payments to decentralized finance and institutional settlement.",
      "Global stablecoin usage has expanded rapidly, signaling that these assets are now functioning as real financial infrastructure rather than speculative instruments. According to data published by Visa Economic Empowerment Institute, global stablecoin transaction volume increased from over $3.5 trillion in 2023 to more than $5.7 trillion in 2024.",
      "This growth reflects rising adoption across payments, trading, and on-chain settlement, particularly in regions where speed, cost efficiency, and access to US dollar liquidity are critical.",
      "At the same time, the total supply of stablecoins has expanded to match this demand. Currently in 2026, total stablecoin supply exceeds $300 billion, following roughly $100 billion of net growth during the previous year. This supply acts as an institutional liquidity float, representing readily deployable capital used for trading, settlement, treasury management, and cross-border flows.",
      "Unlike idle cash in legacy systems, stablecoin balances can be mobilized instantly across exchanges, counterparties, and blockchain networks. The growth of this float underscores why institutions increasingly view stablecoins not just as digital cash equivalents, but as an essential component of modern market structure and OTC liquidity management.",
    ],
    sections: [

    ],
  },
  {
    slug: "crypto-industry-dats",
    title: "Crypto Industry: DATs",
    readingTime: "2 min read",
    excerpt: "Digital Asset Treasuries (DATs) are emerging as an important and often misunderstood investment vehicle within the broader crypto ecosystem. These structures offer investors pseudo exposure to digital assets through operating companies that hold crypto on their balance sheets, helping introduce the concept of crypto ownership to traditional markets in a familiar equity format. Because they trade as public securities, digital asset treasuries can also be held in tax-registered accounts, expanding accessibility for a wider investor base. At the same time, they are fundamentally different from crypto ETF products in structure, risk profile, and purpose, making it important to understand where they fit and where they do not.",
    image: { src: "/images/blog/crypto-industry-dats.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Digital Asset Treasuries (DATs) are emerging as an important and often misunderstood investment vehicle within the broader crypto ecosystem. These structures offer investors pseudo exposure to digital assets through operating companies that hold crypto on their balance sheets, helping introduce the concept of crypto ownership to traditional markets in a familiar equity format. Because they trade as public securities, digital asset treasuries can also be held in tax-registered accounts, expanding accessibility for a wider investor base. At the same time, they are fundamentally different from crypto ETF products in structure, risk profile, and purpose, making it important to understand where they fit and where they do not.",
    ],
    sections: [
      {
        heading: "MARKET FIT",
        paragraphs: [
          "Digital asset treasuries occupy a unique market niche by offering pseudo exposure to crypto through publicly traded equities rather than direct token ownership. This structure allows traditional investors to gain indirect exposure using familiar brokerage accounts, helping bridge the gap between traditional finance and digital assets. Because these securities can be held within tax-advantaged accounts, they lower the friction for investors who are curious about crypto but unwilling or unable to engage with wallets, custody, or on-chain infrastructure.",
        ],
      },
      {
        heading: "EXAMPLE: STRATEGY",
        paragraphs: [
          "Strategy (MSTR), formerly MicroStrategy, is by far the largest DAT in the market, holding approximately 673,783 BTC, making it the largest corporate Bitcoin holder by more than 10x compared to any other public company. The firm began accumulating Bitcoin in 2020, positioning it as a core treasury reserve asset rather than a short-term investment.",
          "Since then, Strategy has consistently added to its holdings across multiple market cycles. At current Bitcoin prices, this strategy has resulted in tens of billions of dollars in unrealized gains, firmly establishing Strategy as the most significant and influential example of a corporate Bitcoin treasury and a primary reference point for investors seeking pseudo exposure to Bitcoin through public equities.",
        ],
      },
      {
        heading: "EXAMPLE: MARA HOLDINGS",
        paragraphs: [
          "MARA Holdings represents a different, but still highly relevant, form of digital asset treasury exposure. As one of the largest publicly traded Bitcoin mining companies, MARA combines operational exposure to Bitcoin production with direct balance sheet ownership. The company currently holds approximately 53,230 BTC, making it the second-largest corporate Bitcoin holder after Strategy. While MARA's product-market fit differs due to the mining nuance, including exposure to energy costs, hash rate, and operational efficiency, its substantial Bitcoin holdings mean the equity remains closely tied to Bitcoin's price performance.",
        ],
      },
      {
        heading: "CRYPTO DATS",
        paragraphs: [
          "While the two examples above are exclusively focused on Bitcoin, crypto-focused digital asset treasuries also play an important role in the broader market. These companies hold diversified baskets of digital assets or maintain exposure beyond Bitcoin, offering investors a different risk and return profile tied to the wider crypto ecosystem.",
          "• Coinbase (COIN): Provides indirect exposure to the broader crypto market through a diversified digital asset treasury and operating leverage tied to trading volumes, custody, and on-chain adoption.",
          "• Galaxy Digital (GLXY): Functions as a hybrid crypto DAT and financial services firm, holding a diversified portfolio of digital assets alongside asset management, trading, and venture investments.",
          "• DeFi Technologies (DEFI): Offers public-market exposure to a basket of digital assets and structured crypto products, positioning itself as a diversified proxy for the growth of decentralized finance and on-chain ecosystems.",
        ],
      },
      {
        heading: "DATS <> ERATREE",
        paragraphs: [
          "Digital asset treasuries represent an increasingly important client segment for EraTree. As DATs scale their balance sheets and actively manage digital asset exposure, reliable liquidity, efficient execution, and seamless settlement become critical requirements. EraTree is purpose-built to support these needs, offering institutional-grade liquidity solutions that allow DATs to deploy, rebalance, and manage capital with confidence as their strategies evolve.",
        ],
      },
    ],
  },
  {
    slug: "bitcoin-institutional-grade-asset",
    title: "Bitcoin: Institutional Grade Asset",
    readingTime: "2 min read",
    excerpt: "Institutional adoption of Bitcoin has accelerated rapidly as regulated access points have matured and familiarity has increased. The launch and growth of spot Bitcoin ETFs, particularly iShares Bitcoin Trust (IBIT), have transformed Bitcoin from a niche allocation into an asset that fits cleanly within traditional investment frameworks.",
    image: { src: "/images/blog/bitcoin-institutional-grade-asset.jpeg", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Institutional adoption of Bitcoin has accelerated rapidly as regulated access points have matured and familiarity has increased. The launch and growth of spot Bitcoin ETFs, particularly iShares Bitcoin Trust (IBIT), have transformed Bitcoin from a niche allocation into an asset that fits cleanly within traditional investment frameworks.",
      "These products allow institutions and advisors to gain exposure through familiar vehicles, removing many of the custody, compliance, and operational hurdles that previously limited participation.",
    ],
    sections: [
      {
        heading: "THE ETF REVOLUTION",
        paragraphs: [
          "The approval of spot Bitcoin ETFs marked a major advancement for institutions and investors seeking direct exposure to Bitcoin without the operational burden that historically came with holding the asset.",
          "Prior to spot ETFs, gaining Bitcoin exposure required managing private keys, navigating custody solutions, and addressing security and compliance concerns that many traditional investors were not equipped to handle. Spot ETFs removed these frictions by wrapping Bitcoin exposure in a regulated product.",
        ],
      },
      {
        heading: "INTEGRATING WITH THE MARKET",
        paragraphs: [
          "The Bitcoin ETF market has scaled rapidly into a meaningful institutional asset class. Globally, Bitcoin ETFs and ETPs now represent more than $170 billion in assets under management, with U.S. spot Bitcoin ETFs accounting for the majority of that total. Since their approval in early 2024, U.S.-listed spot products alone have surpassed $120 billion in AUM, reflecting strong and sustained institutional demand.",
        ],
      },
      {
        heading: "GROWTH OF THE INDUSTRY",
        paragraphs: [
          "BlackRock is the market leader in global asset management. Alongside them, Fidelity Investments has gone a step further than simply offering access to Bitcoin products by publicly discussing portfolio allocation guidance. Fidelity research and advisor commentary have referenced a potential 2% to 5% allocation to Bitcoin for investors who understand its risk and volatility profile.",
          "Bank of America has taken a notable step toward institutional Bitcoin adoption by allowing its wealth management advisors to proactively recommend spot Bitcoin ETFs to eligible clients. Under updated guidance, Bitcoin exposure can now be discussed as part of diversified portfolios, with suggested allocations generally ranging from low single digits based on risk tolerance.",
        ],
      },
    ],
  },
  {
    slug: "how-to-buy-ethereum",
    title: "How to Buy Ethereum",
    readingTime: "2 min read",
    excerpt: "Ethereum was launched in 2015, and in the decade since, it has grown into one of the most important platforms in digital finance. While Bitcoin established the foundation for decentralized value transfer, Ethereum expanded the scope of what blockchains could support by enabling programmable applications and smart contracts.",
    image: { src: "/images/blog/how-to-buy-ethereum.png", alt: "", width: 478, height: 418 },
    logo: false,
    intro: [
      "Ethereum was launched in 2015, and in the decade since, it has grown into one of the most important platforms in digital finance. While Bitcoin established the foundation for decentralized value transfer, Ethereum expanded the scope of what blockchains could support by enabling programmable applications and smart contracts.",
      "Over time, Ethereum has earned increasing credibility as both a network and an asset, becoming a core component of the modern crypto ecosystem and an emerging consideration within diversified portfolios.",
    ],
    sections: [
      {
        heading: "THE HISTORY",
        paragraphs: [
          "Ethereum was proposed in 2013 by Vitalik Buterin and officially launched in 2015 with the goal of creating a decentralized, general-purpose blockchain. Unlike Bitcoin, which was designed primarily as a monetary network, Ethereum introduced smart contracts, allowing developers to build decentralized applications directly on-chain.",
          "In its early years, Ethereum attracted developers, startups, and researchers experimenting with decentralized finance, NFTs, and on-chain governance.",
          "The network has since undergone multiple major upgrades, most notably its transition to proof-of-stake, which significantly improved energy efficiency and reinforced Ethereum's long-term sustainability. This history of continuous development and real-world usage has been central to Ethereum's rise as a foundational blockchain.",
        ],
      },
      {
        heading: "THE GROWTH",
        paragraphs: [
          "As Ethereum matured, an entire economy formed around it. The network now underpins a large portion of decentralized finance, stablecoin settlement, tokenized assets, and on-chain applications. Ethereum has become the primary settlement layer for stablecoins like USDC, institutional DeFi platforms, and tokenized real-world assets, positioning it as critical infrastructure rather than a niche technology.",
          "In parallel, Ethereum has become increasingly integrated with traditional financial markets. Regulated investment products, digital asset treasuries, and institutional custody solutions now support ETH exposure.",
          "This convergence between on-chain infrastructure and traditional capital markets has reinforced Ethereum's role as both a utility-driven network asset and a strategic component of the broader digital asset landscape.",
        ],
      },
      {
        heading: "ERATREE",
        paragraphs: [
          "For institutions, family offices, and high-net-worth individuals, acquiring Ethereum often requires a higher standard of execution and reliability than public exchanges can provide.",
          "EraTree enables clients to access Ethereum efficiently through tailored trade execution, flexible settlement options, and professional service designed for institutional use cases. Whether supporting long-term allocation, treasury management, or on-chain participation, EraTree provides a private and reliable framework for acquiring and managing Ethereum at scale.",
        ],
      },
    ],
  },
];

export function articleBySlug(slug: string): FullArticle | undefined {
  return articles.find((a) => a.slug === slug);
}
