/**
 * Publication dates, kept out of content/articles.ts because that file is
 * regenerated by scripts/scrape-blog.mjs and hand edits there are lost.
 *
 * The source blog carries no dates, so these are assigned weekly working
 * backwards from the most recent post. Replace any value with the real date
 * if it becomes known — nothing derives from the spacing.
 */
export const articleDates: Record<string, string> = {
  "how-to-buy-bitcoin": "2026-08-25",
  "stablecoins-not-all-created-equal": "2026-08-18",
  "crypto-industry-otc": "2026-08-11",
  "bitcoin-monetary-salability": "2026-08-04",
  "how-to-buy-stablecoins": "2026-07-28",
  "stablecoins-institutional-integration": "2026-07-21",
  "crypto-industry-payment": "2026-07-14",
  "bitcoin-absolutely-scarce": "2026-07-07",
  "stablecoins-the-basics": "2026-06-30",
  "crypto-industry-dats": "2026-06-23",
  "bitcoin-institutional-grade-asset": "2026-06-16",
  "how-to-buy-ethereum": "2026-06-09",
};

/** ISO date for a slug, or undefined if the article predates this map. */
export const publishedAt = (slug: string): string | undefined => articleDates[slug];
