/**
 * Scrapes the 12 articles from eratree.io/blog into content/articles.ts and
 * pulls each hero image into public/images/blog/.
 *
 * Committed so the scrape is reproducible rather than a one-off paste. Re-run
 * with `node scripts/scrape-blog.mjs` from the project root.
 *
 * The live pages are plain: <h1>, an intro <p>, then repeated <h2> + <p>
 * sections. That shape drives the crude-but-sufficient regex parsing below —
 * there is no build-time dependency on this script.
 */

import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const ORIGIN = "https://eratree.io";

const SLUGS = [
  "how-to-buy-bitcoin",
  "stablecoins-not-all-created-equal",
  "crypto-industry-otc",
  "bitcoin-monetary-salability",
  "how-to-buy-stablecoins",
  "stablecoins-institutional-integration",
  "crypto-industry-payment",
  "bitcoin-absolutely-scarce",
  "stablecoins-the-basics",
  "crypto-industry-dats",
  "bitcoin-institutional-grade-asset",
  "how-to-buy-ethereum",
];

const IMAGE_DIR = join("public", "images", "blog");

/** Collapse entities and tags down to readable text. */
function clean(html) {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/&[a-z]+;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function matchAll(html, re) {
  return [...html.matchAll(re)].map((m) => clean(m[1])).filter(Boolean);
}

/**
 * Narrows to the single <article> wrapper the live pages use. Without this the
 * site chrome — nav and the footer's address/copyright lines — gets swept in as
 * article body copy.
 */
function articleBody(html) {
  const start = html.indexOf("<article");
  const end = html.indexOf("</article>", start);
  if (start === -1 || end === -1) throw new Error("no <article> container found");
  return html.slice(start, end);
}

/**
 * Walks the body in document order so headings keep their paragraphs. Anything
 * before the first <h2> is the intro.
 */
function parseSections(html) {
  const blocks = [...html.matchAll(/<(h2|p)\b[^>]*>([\s\S]*?)<\/\1>/gi)];
  const intro = [];
  const sections = [];

  for (const [, tag, inner] of blocks) {
    const text = clean(inner);
    if (!text) continue;
    if (tag.toLowerCase() === "h2") {
      sections.push({ heading: text, paragraphs: [] });
    } else if (sections.length === 0) {
      intro.push(text);
    } else {
      sections.at(-1).paragraphs.push(text);
    }
  }
  return { intro, sections };
}

async function scrape(slug) {
  const res = await fetch(`${ORIGIN}/blog/${slug}`);
  if (!res.ok) throw new Error(`${slug}: HTTP ${res.status}`);
  const html = await res.text();

  const body = articleBody(html);
  const title = matchAll(body, /<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)[0] ?? slug;
  const readingTime = (body.match(/(\d+\s*min read)/i)?.[1] ?? "3 min read").toLowerCase();
  const { intro, sections } = parseSections(body);

  // Hero lives behind Next's image optimizer: /_next/image?url=%2Fblogs%2F...
  const encoded = html.match(/\/_next\/image\?url=([^"&]*blogs[^"&]*)/i)?.[1];
  const imagePath = encoded ? decodeURIComponent(encoded) : null;

  let image = null;
  if (imagePath) {
    const ext = imagePath.split(".").pop().split(/[^a-z0-9]/i)[0] || "png";
    const file = `${slug}.${ext}`;
    const bin = await fetch(`${ORIGIN}${imagePath}`);
    if (bin.ok) {
      await writeFile(join(IMAGE_DIR, file), Buffer.from(await bin.arrayBuffer()));
      image = `/images/blog/${file}`;
    }
  }

  return {
    slug,
    title,
    readingTime,
    excerpt: intro[0] ?? "",
    intro,
    sections,
    image,
  };
}

const q = (s) => JSON.stringify(s);

function serialise(articles) {
  const body = articles
    .map(
      (a) => `  {
    slug: ${q(a.slug)},
    title: ${q(a.title)},
    readingTime: ${q(a.readingTime)},
    excerpt: ${q(a.excerpt)},
    image: { src: ${q(a.image ?? "/images/blog-image.png")}, alt: "", width: 478, height: 418 },
    intro: [
${a.intro.map((p) => `      ${q(p)},`).join("\n")}
    ],
    sections: [
${a.sections
  .map(
    (s) => `      {
        heading: ${q(s.heading)},
        paragraphs: [
${s.paragraphs.map((p) => `          ${q(p)},`).join("\n")}
        ],
      },`,
  )
  .join("\n")}
    ],
  },`,
    )
    .join("\n");

  return `/**
 * GENERATED by scripts/scrape-blog.mjs from eratree.io/blog — do not hand-edit.
 * Re-run the script to refresh.
 */

export type ArticleSection = {
  heading: string;
  paragraphs: string[];
};

export type FullArticle = {
  slug: string;
  title: string;
  readingTime: string;
  excerpt: string;
  image: { src: string; alt: string; width: number; height: number };
  intro: string[];
  sections: ArticleSection[];
};

export const articles: FullArticle[] = [
${body}
];

export function articleBySlug(slug: string): FullArticle | undefined {
  return articles.find((a) => a.slug === slug);
}
`;
}

await mkdir(IMAGE_DIR, { recursive: true });

const results = [];
for (const slug of SLUGS) {
  const a = await scrape(slug);
  results.push(a);
  console.log(
    `${a.slug.padEnd(38)} ${String(a.sections.length).padStart(2)} sections  ` +
      `${a.image ? "image ok" : "NO IMAGE"}  ${a.title}`,
  );
}

await writeFile(join("content", "articles.ts"), serialise(results));
console.log(`\nWrote content/articles.ts (${results.length} articles)`);
